spring:
  data:
    mongodb:
      uri: mongodb+srv://AthirsonSilva:%40Potter77@cluster.ye0yagi.mongodb.net/reactive?retryWrites=true&w=majority
      database: reactive

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
 
server:
  port: ${PORT:8000}