spring:
  data:
    mongodb:
      database: products_reactive
      host: localhost
      port: 27017

springdoc:
    api-docs:
      groups:
        enabled: true
      enabled: true
      path: /api-docs
    show-actuator: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web: DEBUG
        
server:
  port: 8000