spring:
  profiles: {SPRING_ENV:dev}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
 
server:
  port: ${PORT:8080}